# Generated by Django 2.0.3 on 2018-05-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClimbingABC', '0003_auto_20180503_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brief',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
